# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e05a68f4e17402e294d6114ef6e69c46e34ca79e9a9a6db8be83b31c695dc5967d544462c72df2f414c8c10e3281f04dbb7360d744cf5deed7665adc29f78850

test:
  secret_key_base: e9e5d777d5eaf4f739e20baebaf1867f7589c2aa7ceb1a504e4138517b27e9a436e89f217375912cb172226a5690f329bcf600b900a9768037b14653bdd590b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
